name: WordPress Theme CI

on:
    push:
        branches: [main]

jobs:
    php-lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.2"

            - name: Check PHP syntax
              run: find . -type f -name "*.php" -exec php -l {} \;
