name: Simple PHP CI

on:
    push:
    pull_request:

jobs:
    php-lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Show folder structure (optional, debug)
              run: ls -R
